try: paraview.simple
except: from paraview.simple import *
paraview.simple._DisableFirstRenderCameraReset()

RenderView1 = CreateRenderView()
RenderView1.LightSpecularColor = [1.0, 1.0, 1.0]
RenderView1.InteractionMode = '3D'
RenderView1.UseTexturedBackground = 0
RenderView1.UseLight = 1
RenderView1.CameraPosition = [-0.03399141757175564, 0.05385020025057429, 0.09620086817625023]
RenderView1.FillLightKFRatio = 3.0
RenderView1.Background2 = [0.0, 0.0, 0.165]
RenderView1.FillLightAzimuth = -10.0
RenderView1.LODResolution = 50.0
RenderView1.BackgroundTexture = []
RenderView1.HeadPose = [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0]
RenderView1.KeyLightAzimuth = 10.0
RenderView1.StencilCapable = 1
RenderView1.LightIntensity = 1.0
RenderView1.CameraFocalPoint = [0.05000000074505807, 0.004999999888241289, 0.00499999988824129]
RenderView1.ImageReductionFactor = 2
RenderView1.CameraViewAngle = 30.0
RenderView1.CameraParallelScale = 0.05049752540739628
RenderView1.EyeAngle = 2.0
RenderView1.HeadLightKHRatio = 3.0
RenderView1.StereoRender = 0
RenderView1.KeyLightIntensity = 0.75
RenderView1.BackLightAzimuth = 110.0
RenderView1.OrientationAxesInteractivity = 0
RenderView1.UseInteractiveRenderingForSceenshots = 0
RenderView1.UseOffscreenRendering = 0
RenderView1.Background = [0.31999694819562063, 0.3400015259021897, 0.4299992370489052]
RenderView1.UseOffscreenRenderingForScreenshots = 1
RenderView1.NonInteractiveRenderDelay = 2
RenderView1.CenterOfRotation = [0.05000000074505806, 0.004999999888241291, 0.004999999888241291]
RenderView1.CameraParallelProjection = 0
RenderView1.CompressorConfig = 'vtkSquirtCompressor 0 3'
RenderView1.HeadLightWarmth = 0.5
RenderView1.MaximumNumberOfPeels = 4
RenderView1.LightDiffuseColor = [1.0, 1.0, 1.0]
RenderView1.StereoType = 'Red-Blue'
RenderView1.DepthPeeling = 1
RenderView1.BackLightKBRatio = 3.5
RenderView1.StereoCapableWindow = 0
RenderView1.CameraViewUp = [0.07230703286217408, 0.9053947828719098, -0.41836823510753784]
RenderView1.LightType = 'HeadLight'
RenderView1.LightAmbientColor = [1.0, 1.0, 1.0]
RenderView1.RemoteRenderThreshold = 3.0
RenderView1.KeyLightElevation = 50.0
RenderView1.CenterAxesVisibility = 1
RenderView1.MaintainLuminance = 0
RenderView1.StillRenderImageReductionFactor = 1
RenderView1.BackLightWarmth = 0.5
RenderView1.FillLightElevation = -75.0
RenderView1.MultiSamples = 0
RenderView1.FillLightWarmth = 0.4
RenderView1.AlphaBitPlanes = 1
RenderView1.LightSwitch = 0
RenderView1.OrientationAxesVisibility = 1
RenderView1.CameraClippingRange = [0.05875881490922426, 0.2273653746216481]
RenderView1.BackLightElevation = 0.0
RenderView1.ViewTime = 0.0
RenderView1.OrientationAxesOutlineColor = [1.0, 1.0, 1.0]
RenderView1.LODThreshold = 5.0
RenderView1.CollectGeometryThreshold = 100.0
RenderView1.UseGradientBackground = 0
RenderView1.KeyLightWarmth = 0.6
RenderView1.OrientationAxesLabelColor = [1.0, 1.0, 1.0]

oneParticleTunnel_ = LegacyVTKReader( guiName="oneParticleTunnel_*", FileNames=['/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_0.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_1.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_2.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_3.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_4.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_5.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_6.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_7.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_8.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_9.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_10.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_11.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_12.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_13.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_14.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_15.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_16.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_17.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_18.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_19.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_20.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_21.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_22.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_23.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_24.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_25.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_26.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_27.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_28.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_29.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_30.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_31.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_32.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_33.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_34.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_35.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_36.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_37.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_38.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_39.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_40.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_41.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_42.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_43.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_44.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_45.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_46.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_47.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_48.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_49.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_50.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_51.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_52.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_53.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_54.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_55.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_56.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_57.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_58.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_59.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_60.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_61.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_62.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_63.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_64.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_65.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_66.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_67.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_68.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_69.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_70.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_71.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_72.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_73.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_74.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_75.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_76.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_77.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_78.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_79.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_80.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/oneParticleTunnel_81.vtk'] )

defaultCloud_ = LegacyVTKReader( guiName="defaultCloud_*", FileNames=['/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_0.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_1.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_2.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_3.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_4.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_5.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_6.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_7.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_8.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_9.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_10.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_11.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_12.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_13.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_14.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_15.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_16.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_17.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_18.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_19.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_20.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_21.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_22.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_23.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_24.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_25.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_26.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_27.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_28.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_29.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_30.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_31.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_32.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_33.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_34.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_35.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_36.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_37.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_38.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_39.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_40.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_41.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_42.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_43.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_44.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_45.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_46.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_47.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_48.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_49.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_50.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_51.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_52.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_53.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_54.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_55.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_56.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_57.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_58.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_59.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_60.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_61.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_62.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_63.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_64.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_65.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_66.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_67.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_68.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_69.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_70.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_71.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_72.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_73.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_74.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_75.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_76.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_77.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_78.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_79.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_80.vtk', '/home/nils/OpenFOAM/nils-1.6-ext/run/GPULagrangianFoam/testCases/oneParticleTunnel/VTK.gpu/lagrangian/defaultCloud/defaultCloud_81.vtk'] )

Glyph1 = Glyph( guiName="Glyph1", RandomMode=1, GlyphTransform="Transform2", GlyphType="Sphere", MaximumNumberofPoints=5000, ScaleMode='scalar', MaskPoints=1, Vectors=['POINTS', 'U'], SetScaleFactor=1.0, Scalars=['POINTS', 'd'], Orient=1 )
Glyph1.GlyphType.StartTheta = 0.0
Glyph1.GlyphType.ThetaResolution = 8
Glyph1.GlyphTransform.Rotate = [0.0, 0.0, 0.0]
Glyph1.GlyphTransform.Translate = [0.0, 0.0, 0.0]
Glyph1.GlyphType.PhiResolution = 8
Glyph1.GlyphType.EndTheta = 360.0
Glyph1.GlyphType.EndPhi = 180.0
Glyph1.GlyphType.Center = [0.0, 0.0, 0.0]
Glyph1.GlyphType.Radius = 0.5
Glyph1.GlyphTransform.Scale = [1.0, 1.0, 1.0]
Glyph1.GlyphType.StartPhi = 0.0

a1_d_PiecewiseFunction = CreatePiecewiseFunction( Points=[0.0, 0.0, 1.0, 1.0] )

a1_d_PVLookupTable = GetLookupTableForArray( "d", 1, Discretize=1, RGBPoints=[0.0010000000474974513, 0.23, 0.299, 0.754, 0.0010000000474974513, 0.706, 0.016, 0.15], UseLogScale=0, VectorComponent=0, NanColor=[0.25, 0.0, 0.0], NumberOfTableValues=256, ColorSpace='Diverging', VectorMode='Magnitude', HSVWrap=0, ScalarRangeInitialized=1.0, LockScalarRange=0 )

SetActiveSource(oneParticleTunnel_)
DataRepresentation1 = Show()
DataRepresentation1.CubeAxesZAxisVisibility = 1
DataRepresentation1.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation1.SelectionPointFieldDataArrayName = 'vtkOriginalPointIds'
DataRepresentation1.SuppressLOD = 0
DataRepresentation1.CubeAxesXGridLines = 0
DataRepresentation1.CubeAxesYAxisTickVisibility = 1
DataRepresentation1.Position = [0.0, 0.0, 0.0]
DataRepresentation1.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation1.SelectionOpacity = 1.0
DataRepresentation1.SelectionPointLabelShadow = 0
DataRepresentation1.CubeAxesYGridLines = 0
DataRepresentation1.OrientationMode = 'Direction'
DataRepresentation1.Source.TipResolution = 6
DataRepresentation1.ScaleMode = 'No Data Scaling Off'
DataRepresentation1.Diffuse = 1.0
DataRepresentation1.SelectionUseOutline = 0
DataRepresentation1.SelectionPointLabelFormat = ''
DataRepresentation1.CubeAxesZTitle = 'Z-Axis'
DataRepresentation1.Specular = 0.1
DataRepresentation1.SelectionVisibility = 1
DataRepresentation1.InterpolateScalarsBeforeMapping = 1
DataRepresentation1.CubeAxesZAxisTickVisibility = 1
DataRepresentation1.Origin = [0.0, 0.0, 0.0]
DataRepresentation1.CubeAxesVisibility = 0
DataRepresentation1.Scale = [1.0, 1.0, 1.0]
DataRepresentation1.SelectionCellLabelJustification = 'Left'
DataRepresentation1.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation1.SelectionCellLabelOpacity = 1.0
DataRepresentation1.CubeAxesInertia = 1
DataRepresentation1.Source = "Arrow"
DataRepresentation1.Source.Invert = 0
DataRepresentation1.Masking = 0
DataRepresentation1.Opacity = 1.0
DataRepresentation1.LineWidth = 1.0
DataRepresentation1.MeshVisibility = 0
DataRepresentation1.Visibility = 1
DataRepresentation1.SelectionCellLabelFontSize = 18
DataRepresentation1.CubeAxesCornerOffset = 0.0
DataRepresentation1.SelectionPointLabelJustification = 'Left'
DataRepresentation1.SelectionPointLabelVisibility = 0
DataRepresentation1.SelectOrientationVectors = ''
DataRepresentation1.CubeAxesTickLocation = 'Inside'
DataRepresentation1.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation1.CubeAxesYAxisVisibility = 1
DataRepresentation1.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation1.Source.ShaftResolution = 6
DataRepresentation1.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation1.SelectScaleArray = ''
DataRepresentation1.CubeAxesYTitle = 'Y-Axis'
DataRepresentation1.ColorAttributeType = 'POINT_DATA'
DataRepresentation1.SpecularPower = 100.0
DataRepresentation1.Texture = []
DataRepresentation1.SelectionCellLabelShadow = 0
DataRepresentation1.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation1.MapScalars = 1
DataRepresentation1.PointSize = 2.0
DataRepresentation1.Source.TipLength = 0.35
DataRepresentation1.SelectionCellLabelFormat = ''
DataRepresentation1.Scaling = 0
DataRepresentation1.StaticMode = 0
DataRepresentation1.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation1.Source.TipRadius = 0.1
DataRepresentation1.EdgeColor = [0.0, 0.0, 0.5000076295109483]
DataRepresentation1.CubeAxesXAxisTickVisibility = 1
DataRepresentation1.SelectionCellLabelVisibility = 0
DataRepresentation1.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation1.Representation = 'Wireframe'
DataRepresentation1.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation1.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation1.Orientation = [0.0, 0.0, 0.0]
DataRepresentation1.CubeAxesXTitle = 'X-Axis'
DataRepresentation1.ScalarOpacityUnitDistance = 0.046877750011209626
DataRepresentation1.BackfaceOpacity = 1.0
DataRepresentation1.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation1.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation1.Ambient = 0.0
DataRepresentation1.SelectionPointLabelFontSize = 18
DataRepresentation1.ScaleFactor = 1.0
DataRepresentation1.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation1.Source.ShaftRadius = 0.03
DataRepresentation1.ScalarOpacityFunction = []
DataRepresentation1.SelectMaskArray = ''
DataRepresentation1.SelectionLineWidth = 2.0
DataRepresentation1.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation1.CubeAxesXAxisVisibility = 1
DataRepresentation1.Interpolation = 'Gouraud'
DataRepresentation1.SelectMapper = 'Projected tetra'
DataRepresentation1.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation1.SelectionCellLabelItalic = 0
DataRepresentation1.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation1.CubeAxesZGridLines = 0
DataRepresentation1.ExtractedBlockIndex = 0
DataRepresentation1.SelectionPointLabelOpacity = 1.0
DataRepresentation1.Pickable = 1
DataRepresentation1.CustomBoundsActive = [0, 0, 0]
DataRepresentation1.SelectionRepresentation = 'Wireframe'
DataRepresentation1.SelectionPointLabelBold = 0
DataRepresentation1.ColorArrayName = ''
DataRepresentation1.SelectionPointLabelItalic = 0
DataRepresentation1.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation1.LookupTable = []
DataRepresentation1.SelectionPointSize = 5.0
DataRepresentation1.SelectionCellLabelBold = 0
DataRepresentation1.Orient = 0

SetActiveSource(defaultCloud_)
DataRepresentation2 = Show()
DataRepresentation2.CubeAxesZAxisVisibility = 1
DataRepresentation2.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation2.SelectionPointFieldDataArrayName = 'vtkOriginalPointIds'
DataRepresentation2.SuppressLOD = 0
DataRepresentation2.CubeAxesXGridLines = 0
DataRepresentation2.CubeAxesYAxisTickVisibility = 1
DataRepresentation2.Position = [0.0, 0.0, 0.0]
DataRepresentation2.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation2.SelectionOpacity = 1.0
DataRepresentation2.SelectionPointLabelShadow = 0
DataRepresentation2.CubeAxesYGridLines = 0
DataRepresentation2.OrientationMode = 'Direction'
DataRepresentation2.Source.TipResolution = 6
DataRepresentation2.ScaleMode = 'No Data Scaling Off'
DataRepresentation2.Diffuse = 1.0
DataRepresentation2.SelectionUseOutline = 0
DataRepresentation2.CubeAxesZTitle = 'Z-Axis'
DataRepresentation2.Specular = 0.1
DataRepresentation2.SelectionVisibility = 1
DataRepresentation2.InterpolateScalarsBeforeMapping = 1
DataRepresentation2.CubeAxesZAxisTickVisibility = 1
DataRepresentation2.Origin = [0.0, 0.0, 0.0]
DataRepresentation2.CubeAxesVisibility = 0
DataRepresentation2.Scale = [1.0, 1.0, 1.0]
DataRepresentation2.SelectionCellLabelJustification = 'Left'
DataRepresentation2.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation2.SelectionCellLabelOpacity = 1.0
DataRepresentation2.Source = "Arrow"
DataRepresentation2.Source.Invert = 0
DataRepresentation2.Masking = 0
DataRepresentation2.Opacity = 1.0
DataRepresentation2.LineWidth = 1.0
DataRepresentation2.SelectionPointSize = 5.0
DataRepresentation2.Visibility = 1
DataRepresentation2.SelectionCellLabelFontSize = 18
DataRepresentation2.CubeAxesCornerOffset = 0.0
DataRepresentation2.SelectionPointLabelJustification = 'Left'
DataRepresentation2.Ambient = 0.0
DataRepresentation2.SelectOrientationVectors = ''
DataRepresentation2.CubeAxesTickLocation = 'Inside'
DataRepresentation2.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation2.CubeAxesYAxisVisibility = 1
DataRepresentation2.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation2.Source.ShaftResolution = 6
DataRepresentation2.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation2.SelectScaleArray = ''
DataRepresentation2.CubeAxesYTitle = 'Y-Axis'
DataRepresentation2.ColorAttributeType = 'POINT_DATA'
DataRepresentation2.SpecularPower = 100.0
DataRepresentation2.Texture = []
DataRepresentation2.SelectionCellLabelShadow = 0
DataRepresentation2.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation2.MapScalars = 1
DataRepresentation2.PointSize = 2.0
DataRepresentation2.Source.TipLength = 0.35
DataRepresentation2.SelectionCellLabelFormat = ''
DataRepresentation2.Scaling = 0
DataRepresentation2.StaticMode = 0
DataRepresentation2.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation2.Source.TipRadius = 0.1
DataRepresentation2.EdgeColor = [0.0, 0.0, 0.5000076295109483]
DataRepresentation2.CubeAxesXAxisTickVisibility = 1
DataRepresentation2.SelectionCellLabelVisibility = 0
DataRepresentation2.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation2.Representation = 'Surface'
DataRepresentation2.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation2.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation2.Orientation = [0.0, 0.0, 0.0]
DataRepresentation2.CubeAxesXTitle = 'X-Axis'
DataRepresentation2.CubeAxesInertia = 1
DataRepresentation2.BackfaceOpacity = 1.0
DataRepresentation2.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation2.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation2.SelectionPointLabelVisibility = 0
DataRepresentation2.SelectionPointLabelFontSize = 18
DataRepresentation2.ScaleFactor = 1.0
DataRepresentation2.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation2.Source.ShaftRadius = 0.03
DataRepresentation2.SelectMaskArray = ''
DataRepresentation2.SelectionLineWidth = 2.0
DataRepresentation2.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation2.CubeAxesXAxisVisibility = 1
DataRepresentation2.Interpolation = 'Gouraud'
DataRepresentation2.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation2.SelectionCellLabelItalic = 0
DataRepresentation2.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation2.CubeAxesZGridLines = 0
DataRepresentation2.SelectionPointLabelFormat = ''
DataRepresentation2.SelectionPointLabelOpacity = 1.0
DataRepresentation2.Pickable = 1
DataRepresentation2.CustomBoundsActive = [0, 0, 0]
DataRepresentation2.SelectionRepresentation = 'Wireframe'
DataRepresentation2.SelectionPointLabelBold = 0
DataRepresentation2.ColorArrayName = ''
DataRepresentation2.SelectionPointLabelItalic = 0
DataRepresentation2.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation2.LookupTable = []
DataRepresentation2.MeshVisibility = 0
DataRepresentation2.SelectionCellLabelBold = 0
DataRepresentation2.Orient = 0

SetActiveSource(Glyph1)
DataRepresentation3 = Show()
DataRepresentation3.CubeAxesZAxisVisibility = 1
DataRepresentation3.SelectionPointLabelColor = [0.5, 0.5, 0.5]
DataRepresentation3.SelectionPointFieldDataArrayName = 'vtkOriginalPointIds'
DataRepresentation3.SuppressLOD = 0
DataRepresentation3.CubeAxesXGridLines = 0
DataRepresentation3.CubeAxesYAxisTickVisibility = 1
DataRepresentation3.Position = [0.0, 0.0, 0.0]
DataRepresentation3.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation3.SelectionOpacity = 1.0
DataRepresentation3.SelectionPointLabelShadow = 0
DataRepresentation3.CubeAxesYGridLines = 0
DataRepresentation3.OrientationMode = 'Direction'
DataRepresentation3.Source.TipResolution = 6
DataRepresentation3.ScaleMode = 'No Data Scaling Off'
DataRepresentation3.Diffuse = 1.0
DataRepresentation3.SelectionUseOutline = 0
DataRepresentation3.CubeAxesZTitle = 'Z-Axis'
DataRepresentation3.Specular = 0.1
DataRepresentation3.SelectionVisibility = 1
DataRepresentation3.InterpolateScalarsBeforeMapping = 1
DataRepresentation3.CubeAxesZAxisTickVisibility = 1
DataRepresentation3.Origin = [0.0, 0.0, 0.0]
DataRepresentation3.CubeAxesVisibility = 0
DataRepresentation3.Scale = [1.0, 1.0, 1.0]
DataRepresentation3.SelectionCellLabelJustification = 'Left'
DataRepresentation3.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation3.SelectionCellLabelOpacity = 1.0
DataRepresentation3.Source = "Arrow"
DataRepresentation3.Source.Invert = 0
DataRepresentation3.Masking = 0
DataRepresentation3.Opacity = 1.0
DataRepresentation3.LineWidth = 1.0
DataRepresentation3.SelectionPointSize = 5.0
DataRepresentation3.Visibility = 1
DataRepresentation3.SelectionCellLabelFontSize = 18
DataRepresentation3.CubeAxesCornerOffset = 0.0
DataRepresentation3.SelectionPointLabelJustification = 'Left'
DataRepresentation3.Ambient = 0.0
DataRepresentation3.SelectOrientationVectors = ''
DataRepresentation3.CubeAxesTickLocation = 'Inside'
DataRepresentation3.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation3.CubeAxesYAxisVisibility = 1
DataRepresentation3.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation3.Source.ShaftResolution = 6
DataRepresentation3.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation3.SelectScaleArray = ''
DataRepresentation3.CubeAxesYTitle = 'Y-Axis'
DataRepresentation3.ColorAttributeType = 'POINT_DATA'
DataRepresentation3.SpecularPower = 100.0
DataRepresentation3.Texture = []
DataRepresentation3.SelectionCellLabelShadow = 0
DataRepresentation3.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation3.MapScalars = 1
DataRepresentation3.PointSize = 2.0
DataRepresentation3.Source.TipLength = 0.35
DataRepresentation3.SelectionCellLabelFormat = ''
DataRepresentation3.Scaling = 0
DataRepresentation3.StaticMode = 0
DataRepresentation3.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation3.Source.TipRadius = 0.1
DataRepresentation3.EdgeColor = [0.0, 0.0, 0.5000076295109483]
DataRepresentation3.CubeAxesXAxisTickVisibility = 1
DataRepresentation3.SelectionCellLabelVisibility = 0
DataRepresentation3.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation3.Representation = 'Surface'
DataRepresentation3.CustomBounds = [0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
DataRepresentation3.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation3.Orientation = [0.0, 0.0, 0.0]
DataRepresentation3.CubeAxesXTitle = 'X-Axis'
DataRepresentation3.CubeAxesInertia = 1
DataRepresentation3.BackfaceOpacity = 1.0
DataRepresentation3.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation3.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation3.SelectionPointLabelVisibility = 0
DataRepresentation3.SelectionPointLabelFontSize = 18
DataRepresentation3.ScaleFactor = 1.0
DataRepresentation3.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation3.Source.ShaftRadius = 0.03
DataRepresentation3.SelectMaskArray = ''
DataRepresentation3.SelectionLineWidth = 2.0
DataRepresentation3.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation3.CubeAxesXAxisVisibility = 1
DataRepresentation3.Interpolation = 'Gouraud'
DataRepresentation3.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation3.SelectionCellLabelItalic = 0
DataRepresentation3.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation3.CubeAxesZGridLines = 0
DataRepresentation3.SelectionPointLabelFormat = ''
DataRepresentation3.SelectionPointLabelOpacity = 1.0
DataRepresentation3.Pickable = 1
DataRepresentation3.CustomBoundsActive = [0, 0, 0]
DataRepresentation3.SelectionRepresentation = 'Wireframe'
DataRepresentation3.SelectionPointLabelBold = 0
DataRepresentation3.ColorArrayName = 'd'
DataRepresentation3.SelectionPointLabelItalic = 0
DataRepresentation3.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation3.LookupTable = a1_d_PVLookupTable
DataRepresentation3.MeshVisibility = 0
DataRepresentation3.SelectionCellLabelBold = 0
DataRepresentation3.Orient = 0

Render()
