#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x
set -e

# Hack
cd GPUTracking
make
mv libgputracking.so $FOAM_USER_LIBBIN
cd ..
wmake libso GPULagrangian
wmake GPULagrangianFoam
wmake tests
wmake genRandCloud
